### ISSUE TITLE
Support for nested unit test folders in spec folder.

### ISSUE THREAD

**Issue by jdshkolnik** [vassilvk/slacker#1]
"App.Db.Slacker\spec\config\config_value_code_part.rb" works fine.

"App.Db.Slacker\spec\bc\config\config_value_code_part.rb" errors out.

**Comment by jdshkolnik** [comment]
Never mind, I misunderstood the root cause.

**Comment by jdshkolnik** [comment]
Actually, I'm not sure if it's this or something related. Let's discuss when you have a chance.

**Comment by jdshkolnik** [comment]
I think there's also an issue with paths containing spaces.

**Comment by vassilvk** [comment]
If getting issues with spaces in folder\file names while running in Visual Studio, but not while running on the console, you are experiencing an issue with Slacker Runner (https://github.com/ornatwork/SlackerRunner)
