### ISSUE TITLE
specs running multiple times

### ISSUE THREAD

**Issue by leandroblemos** [vassilvk/slacker#16]
Hello there!
I created a very simple test to evaluate the framework. It works great in VS but when I integrated with my build the tests run 3 times each.

Any idea, please?
![image](https://user-images.githubusercontent.com/23246898/28804585-0fd40904-7619-11e7-9c1c-92797a808b7c.png)

**Comment by jdshkolnik** [comment]
This relates to [SlackerRunner](https://github.com/deloitte-solvas/SlackerRunner) rather than Slacker itself. Can we see the content of the cs file containing the call to SlackerRunner?

**Comment by ornatwork** [comment]
Yes, this is a SlackerRunner issue, SlackerRunner is the intergration into VS, I have migrated the  [issue to the SlackerRunner project](https://github.com/deloitte-solvas/SlackerRunner/issues/16) please close this one.

**Comment by jdshkolnik** [comment]
Only @vassilvk has rights to close here.

**Comment by leandroblemos** [comment]
Thank you, I'll upload the .cs file to on the SlackRunner project. we have just 2 simple specs.... I'm wondering if the build is duplicating my files
