### ISSUE TITLE
Create passed_examples and failed_examples if missing

### ISSUE THREAD

**Issue by vassilvk** [vassilvk/slacker#27]
`slacker` fails if folders `debug/passed_examples` and `debug/failed_examples` are missing.
Those folders are scaffolded empty, which makes it challenging to put in a git repository.
One can place a `.gitignore` file in them to make git commit them, but `slacker` empties them on every run.

Solve this by having `slacker` create these folders if  missing.
Also, add a `.gitignore` file at the root of the project to make sure the folders are never committed by git.

**Comment by vassilvk** [comment]
@jdshkolnik, can you describe the use case where you see slacker failures on missing debug folders? The current version of `slacker` already creates the folders if missing.

**Comment by jdshkolnik** [comment]
It does? I haven't tested it in a while so I've been operating under the assumption of past behavior.

**Comment by jdshkolnik** [comment]
It works. The only thing missing is the project-level gitignore.

**Comment by vassilvk** [comment]
Closing in favor of a new issue re: .gitignore

**Comment by vassilvk** [comment]
#29
