### ISSUE TITLE
Add .gitignore at root of scaffold project

### ISSUE THREAD

**Issue by vassilvk** [vassilvk/slacker#29]
Add a `.gitignore` file at the root of the scaffold project created by `slacker_new`.
Add `debug/` to it to ignore `debug` folders.

**Comment by jdshkolnik** [comment]
Why does the gitignore file not have a preceding dot in its file name?

**Comment by jdshkolnik** [comment]
@vassilvk See question above.

**Comment by vassilvk** [comment]
@jdshkolnik, see comment in commit in bin/slacker_new.
Also, try creating a new project with slacker_new -- observe the dot prefix in new project.

**Comment by vassilvk** [comment]
Short answer - because sometimes things are not as simple as they seem ;)
