### ISSUE TITLE
SPROC module raise error handling

### ISSUE THREAD

**Issue by GJPVN** [vassilvk/slacker#31]
Hi

I use TSQL RAISE Error command in the stored procedure for any error condition. 
Am getting test failed result in slacker. How to check expected result in such cases. 

Sample output from Stored Procedure Execution 👍 
__Msg 50000, Level 16, State 1, Procedure error_handler, Line 99
Please enter Actual Date/Time for the event 'Arrived' in Leg '1'.__

**Comment by vassilvk** [comment]
If this is an error you expect to be raised under the test conditions, you should use one of the forms of the [raise_error matcher](https://relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/raise-error-matcher).

**Comment by vassilvk** [comment]
@GJPVN, does this answer your question?

**Comment by vassilvk** [comment]
Closing the issue.
@GJPVN, if the above does not answer your question, please reopen.
