### ISSUE TITLE
SQL date comparison strips last character and fails

### ISSUE THREAD

**Issue by pmalecka** [vassilvk/slacker#35]
Hi Vassilvk,

while putting together some test cases I stumbled upon a strange issue with CSV Matching:
SQL ODBC,
Data Type in SQL: date
Value in CSV: 2017-11-01

expect(sql.select_date).to match('date.csv')
throws the following error:
Field "date", Record 1: Expected value "2017-11-01", got "2017-11-0  "

The Date seems to be parsed incorrectly from the result of the SQL Select.
The file is formatted as ANSI, I am using ODBC named pipe connection to a local machine.

**Comment by vassilvk** [comment]
@pmalecka, there seems to be an issue with the conversion of date to string.
I am planning to refactor the CSV date matching logic in the fix of #34. In the meantime, you can work around the issue by converting the dates to varchar at the statement you are comparing with the CSV file.

**Comment by pmalecka** [comment]
thanks for the swift response. That is exactly what I had done - convert to varchar and then the csv compare works as expected.
What I wanted to point out that the matching logic is somewhat broken for Date as well as for DateTime (as metioned in #34).

**Comment by vassilvk** [comment]
@pmalecka - Commit b019ffec6b143ca487b85f6b58634126ef545660 adds proper support for `DATETIME` for both `odbc` and `tiny_tds` drivers.

It also adds support for `DATE`, but unfortunately it is only supported when using `tiny_tds`.

The problem you are experiencing comes from the fact that when returning a `DATE`, the ODBC driver converts it to a string, cuts off the last character and adds two spaces. Pretty weird, I know, but it is what it is.

When dealing with dates, I recommend to do one of the following:
  - use `DATETIME`, or...
  - use `tiny_tds` which supports both `DATE` and `DATETIME`, or...
  - convert to string at the source as per our previous discussion

**Comment by vassilvk** [comment]
Closing as issue is caused by ODBC driver. Please consider one of the alternatives above.

**Comment by pmalecka** [comment]
all right. I am currently using named pipes, so I am stuck with ODBC. Thanks for looking into it, though.
