### ISSUE TITLE
Does load_csv insert data into the real table on target database?

### ISSUE THREAD

**Issue by Missshu** [vassilvk/slacker#38]
Hi Guys, thanks for developing slacker for SQL unit testing. I have just started learning about it and I have a question: when we use load_csv , is it going to insert the data  into the real table on the target database permanently or is it going to insert into a memory table? From the usage description, it seems like  it inserts the data from the .csv file into the real table on the target database. 

Thanks,

**Comment by jdshkolnik** [comment]
It does insert into real tables but will always rollback between each test. You can see the SQL it produces per test in the debug folder.

**Comment by vassilvk** [comment]
Hi @Missshu,

The `sproc` helper method takes an arbitrary number of input and output parameters.

Something's wrong with the way these parameters are passed in your test.
Can you post the full body of the test, including the place where variable `timepintStausTable` is instantiated?

**Comment by Missshu** [comment]
Hi @vassilvk ,

Here is the full body of the test:

it'executes my_Stored_Procedure by passing TimepointStatus procedure as a parameter' do
 
  timepintStausTable = TableVariable.new('@timepintStausTable','dbo.TimepointStatusTable', 
  ['StudyId','StudyCode','SubjectId','Subject','Timepoint','DerivedOverallTimepointStatus','TimepointStatus','Include'],
  [11,11111,91,11161,'SCREENING','Analyzed','Complete',1])
  
  result  = sproc('my_Stored_Procedure', 11111, timepintStausTable)
  expect(result.count).to be == 4
  
  end

dbo.TimepointStatusTable has already been created as a user defined table type in the database  and I am just calling it here.

Thank you.

**Comment by vassilvk** [comment]
You will get this error if you misspelled the name of the table data type.

To troubleshoot this, run `slacker`, then look into folder `./debug/failed_examples`. You will find the actual SQL code generated by `slacker` for all failed tests.

Find the code which corresponds to the test you are working on, open it up in SQL Management Studio and try to run it there - this will give you a better understanding of the issue you are dealing with.

**Comment by vassilvk** [comment]
@Missshu - I am closing this issue.
Please let me know if the above does not resolve it for you and I will open another issue.
