### ISSUE TITLE
Enable testing of Azure database

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [vassilvk/slacker#39]
When using TinyTds I cannot connect to an Azure Database.  It appears that TinyTds Client constructor has a :azure parameter that needs to be set true for using Azure.

Can this be exposed in the database.yml ?  Sorry, I'm not a Ruby developer otherwise I would have created a PR for this.

**Comment by vassilvk** [comment]
@RoyC-Retail-Assist - can you update slacker to 1.0.24 and give it a try?

**Comment by RoyC-Retail-Assist** [comment]
That worked great.

Thank you :thumbsup:
