### ISSUE TITLE
slacker_new my_project not working for me

### ISSUE THREAD

**Issue by rodsantest1** [vassilvk/slacker#42]
I installed ruby and then slacker. Added ruby bin to environment.
open command line and typed **slacker_new my_project** but command was not found.

Any ideas?

**Comment by vassilvk** [comment]
Not sure what the problem might be.
Can you check if `slacker` and `slacker_new` are in your Ruby bin folder (for example `c:\Ruby25-x64\bin\`)?
Also, can you make sure that `bin` folder is in your `PATH` variable as seen by the console?

**Comment by vassilvk** [comment]
@rodsantest1 - I am closing this issue.
If there's anything you need to add, please reopen.
